In [3]:
# https://platform.olimpiada-ai.ro/en/problems/220

import os
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from scipy.spatial.distance import mahalanobis

In [4]:
train = pl.read_csv("/kaggle/input/datasets/abukanabek/credit-card-fraud/train.csv")
test = pl.read_csv("/kaggle/input/datasets/abukanabek/credit-card-fraud/test.csv")
subm = pl.read_csv("/kaggle/input/datasets/abukanabek/credit-card-fraud/sample_output.csv")

In [5]:
train.shape, test.shape, subm.shape

((227845, 32), (56962, 31), (56964, 3))

In [6]:
train.head()

shape: (5, 32)
┌─────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────┐
│ id  ┆ Time     ┆ V1        ┆ V2        ┆ … ┆ V27       ┆ V28       ┆ Amount ┆ Class │
│ --- ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---    ┆ ---   │
│ i64 ┆ f64      ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64    ┆ i64   │
╞═════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════╡
│ 1   ┆ 143352.0 ┆ 1.955041  ┆ -0.380783 ┆ … ┆ 0.045168  ┆ -0.047145 ┆ 9.99   ┆ 0     │
│ 2   ┆ 117173.0 ┆ -0.400975 ┆ -0.626943 ┆ … ┆ -0.370469 ┆ -0.144792 ┆ 45.9   ┆ 0     │
│ 3   ┆ 149565.0 ┆ 0.072509  ┆ 0.820566  ┆ … ┆ 0.206395  ┆ 0.070288  ┆ 11.99  ┆ 0     │
│ 4   ┆ 93670.0  ┆ -0.535045 ┆ 1.014587  ┆ … ┆ -0.093013 ┆ -0.064931 ┆ 117.44 ┆ 0     │
│ 5   ┆ 82655.0  ┆ -4.026938 ┆ 1.897371  ┆ … ┆ 0.286904  ┆ -0.322672 ┆ 25.76  ┆ 0     │
└─────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────┘

In [7]:
train['Class'].value_counts()

shape: (2, 2)
┌───────┬────────┐
│ Class ┆ count  │
│ ---   ┆ ---    │
│ i64   ┆ u32    │
╞═══════╪════════╡
│ 1     ┆ 394    │
│ 0     ┆ 227451 │
└───────┴────────┘

In [8]:
subtask1 = float((train.filter(pl.col('Class')==1)['Amount'] > train.filter(pl.col('Class')==0)['Amount'].mean()).sum())
subtask1

127.0

In [9]:
numeric_features = ['Amount'] + [f'V{i}' for i in range(1, 28+1)]

numerics = train.filter(pl.col('Class')==1).select(numeric_features).to_numpy()

mean_vector = numerics.mean(axis=0)
cov_matrix = np.cov(numerics.T)

eps = 1e-6
cov_matrix += eps * np.eye(cov_matrix.shape[0])
inv_cov_matrix = np.linalg.inv(cov_matrix)

mean_vector.shape, inv_cov_matrix.shape

((29,), (29, 29))

In [10]:
subtask2 = round(np.array([mahalanobis(mean_vector, numerics[i], inv_cov_matrix) for i in range(len(numerics))]).mean().item(), 2)
subtask2

5.1

In [11]:
from sklearn.model_selection import train_test_split
from catboost import Pool

features = ['Time'] + numeric_features
target_col = 'Class'

X, y = train.select(features).to_numpy(), train.select(target_col).to_numpy()
X_test = test.select(features).to_numpy()

X_train, X_valid, y_train, y_valid = train_test_split(X, y, stratify=y, test_size=0.1, random_state=42)

train_pool = Pool(X_train, y_train)
valid_pool = Pool(X_valid, y_valid)

In [12]:
from catboost import CatBoostClassifier

params = {
    'iterations': 500,
    'loss_function': 'Logloss',
    'metric_period': 100,
    'eval_metric': 'F1',
    'random_state': 42,
    'max_depth': 2,
    'learning_rate': 0.1
}

model = CatBoostClassifier(**params)

model.fit(train_pool, eval_set=valid_pool)

0:	learn: 0.0000000	test: 0.0000000	best: 0.0000000 (0)	total: 100ms	remaining: 50s
100:	learn: 0.8438949	test: 0.8421053	best: 0.8421053 (100)	total: 2.2s	remaining: 8.69s
200:	learn: 0.8686244	test: 0.8533333	best: 0.8533333 (200)	total: 4.25s	remaining: 6.33s
300:	learn: 0.8854489	test: 0.8648649	best: 0.8648649 (300)	total: 6.3s	remaining: 4.16s
400:	learn: 0.8957055	test: 0.8648649	best: 0.8648649 (300)	total: 8.31s	remaining: 2.05s
499:	learn: 0.9054878	test: 0.8767123	best: 0.8767123 (499)	total: 10.4s	remaining: 0us

bestTest = 0.8767123288
bestIteration = 499

CatBoostClassifier(eval_metric='F1', iterations=500, learning_rate=0.1, loss_function='Logloss', max_depth=2, metric_period=100, random_state=42)

In [13]:
y_pred = model.predict(X_test)
y_pred, np.bincount(y_pred)

(array([1, 0, 0, ..., 0, 0, 0]), array([56883,    79]))

In [14]:
subm = subm.with_columns(answer=np.concatenate([np.array([subtask1, subtask2]), y_pred]))

In [15]:
subm.write_csv('submission.csv')
subm.head(10)

shape: (10, 3)
┌───────────┬─────────────┬────────┐
│ subtaskID ┆ datapointID ┆ answer │
│ ---       ┆ ---         ┆ ---    │
│ i64       ┆ i64         ┆ f64    │
╞═══════════╪═════════════╪════════╡
│ 1         ┆ 1           ┆ 127.0  │
│ 2         ┆ 1           ┆ 5.1    │
│ 3         ┆ 227846      ┆ 1.0    │
│ 3         ┆ 227847      ┆ 0.0    │
│ 3         ┆ 227848      ┆ 0.0    │
│ 3         ┆ 227849      ┆ 0.0    │
│ 3         ┆ 227850      ┆ 0.0    │
│ 3         ┆ 227851      ┆ 0.0    │
│ 3         ┆ 227852      ┆ 0.0    │
│ 3         ┆ 227853      ┆ 0.0    │
└───────────┴─────────────┴────────┘