In [ ]:
# https://platform.olimpiada-ai.ro/en/problems/92
# https://platform.olimpiada-ai.ro/en/problems/93

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

In [140]:
data = pd.read_csv("/kaggle/input/datasets/abukanabek/museums-romania-9-10/muzee.csv")
subm = pd.read_csv("/kaggle/input/datasets/abukanabek/museums-romania-9-10/sample_output.csv")

data.shape, subm.shape

((1008, 44), (1056, 3))

In [141]:
data.head(2)

,_id,codul entității muzeale,identificatorul înregistrării,județul,denumirea (română),denumirea cu localitate (română),denumirea (engleză),denumirea cu localitate (engleză),localitatea,unitatea administrativă,...,codul LMI al clădirii,codul SIRUTA al localității,data ultimei modificări,profilul principal (engleză),ordinul de acreditare,categoria (română),categoria (engleză),latitudine,longitudine,coordonatele
0,1,7083504,8,București,"Muzeul Memorial ""Dr. Victor Babeș""","Muzeul Memorial ""Dr. Victor Babeș"" - BUCUREȘTI",Dr. Victor Babeș Memorial Museum,Dr. Victor Babeș Memorial Museum - BUCHAREST,BUCUREȘTI,NaN,...,B-II-m-B-19267,179141.0,30.09.2013 12:50:47,Memorials -,NaN,Muzeu municipal,City museum,"44,460065","26,091329",muzeu
1,2,7300205,9,București,"Muzeul de Artă Veche Apuseană ""ing. Dumitru Mi...","Muzeul de Artă Veche Apuseană ""ing. Dumitru Mi...",Eng. Dumitru Minovici Western Old Art Museum,Eng. Dumitru Minovici Western Old Art Museum -...,BUCUREȘTI,NaN,...,B-II-m-A-19206,179141.0,05.12.2013 11:37:34,NaN,NaN,Muzeu în subordinea Academiei Române,Museum under the Romanian Academy,"44,484256","26,074651",muzeu

In [142]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 44 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   _id                                    1008 non-null   int64
 1   codul entității muzeale                1008 non-null   int64
 2   identificatorul înregistrării          1008 non-null   int64
 3   județul                                1008 non-null   object
 4   denumirea (română)                     1008 non-null   object
 5   denumirea cu localitate (română)       1008 non-null   object
 6   denumirea (engleză)                    1008 non-null   object
 7   denumirea cu localitate (engleză)      1008 non-null   object
 8   localitatea                            1008 non-null   object
 9   unitatea administrativă                478 non-null    object
 10  adresa                                 723 non-null    object
 11  codul poștal                           1008 non-null   object
 12  telefon                                778 non-null    object
 13  data ultimei confirmări a telefonului  476 non-null    object
 14  fax                                    345 non-null    object
 15  data ultimei confirmări a faxului      382 non-null    object
 16  programul (română)                     887 non-null    object
 17  programul (engleză)                    887 non-null    object
 18  anul înființării                       763 non-null    object
 19  descrierea (română)                    1007 non-null   object
 20  descrierea sumară (română)             938 non-null    object
 21  descrierea sumară (engleză)            1007 non-null   object
 22  descrierea clădirii (română)           328 non-null    object
 23  descrierea clădirii (engleză)          240 non-null    object
 24  istoric (română)                       312 non-null    object
 25  istoric (engleză)                      198 non-null    object
 26  acces (română)                         524 non-null    object
 27  access (engleză)                       519 non-null    object
 28  URL                                    607 non-null    object
 29  e-mail                                 481 non-null    object
 30  director                               519 non-null    object
 31  codul instituției                      992 non-null    object
 32  descrierea (engleză)                   553 non-null    object
 33  profilul principal (română)            1005 non-null   object
 34  codul LMI al clădirii                  349 non-null    object
 35  codul SIRUTA al localității            1007 non-null   float64
 36  data ultimei modificări                1008 non-null   object
 37  profilul principal (engleză)           154 non-null    object
 38  ordinul de acreditare                  50 non-null     object
 39  categoria (română)                     815 non-null    object
 40  categoria (engleză)                    763 non-null    object
 41  latitudine                             1006 non-null   object
 42  longitudine                            1006 non-null   object
 43  coordonatele                           1006 non-null   object
dtypes: float64(1), int64(3), object(40)
memory usage: 346.6+ KB

In [143]:
subm.loc[0:3, 'answer'] = [
    len(data),
    (data['județul']=='București').sum(),
    len(data.columns[(data.isna().sum() > 0).values]),
    int(data['anul înființării'].value_counts().index[0])
]

In [144]:
subm.iloc[4:4+data['județul'].nunique(), 2] = list(
    map(
        data['județul'].value_counts().to_dict().get, subm.iloc[4:4+42, 0]
    )
)

In [145]:
all(subm.iloc[4+data['județul'].nunique():4+data['județul'].nunique()+data.shape[0]]['id'].values == data['_id'].astype('str').values)

True

In [146]:
subm.iloc[4+data['județul'].nunique():4+data['județul'].nunique()+data.shape[0], 2] = (
    (
        (
            data.shape[1] - data.isna().sum(axis=1)
        ) 
        / data.shape[1]
    )
    .map(lambda x: round(100*x, 2))
)

/tmp/ipykernel_55/1945738903.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[81.82 81.82 77.27 ... 72.73 61.36 79.55]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  subm.iloc[4+data['județul'].nunique():4+data['județul'].nunique()+data.shape[0], 2] = (

In [147]:
subm.iloc[-2:, 2] = [
    round(
        subm
        .iloc[4+data['județul'].nunique():4+data['județul'].nunique()+data.shape[0], 2]
        .mean(), 
        2
    ),
    round(
        (
            subm.iloc[4+data['județul'].nunique():4+data['județul'].nunique()+data.shape[0], 2]
            == 
            (
                subm
                .iloc[4+data['județul'].nunique():4+data['județul'].nunique()+data.shape[0], 2]
                .max()
            )
        ).mean()*100, 2
    )
]

In [148]:
subm.to_csv("submission.csv", index=False)

subm

        id  subtaskID   answer
0        1          1  1008.00
1        2          2    59.00
2        3          3    33.00
3        4          4  2006.00
4     Alba          5    60.00
...    ...        ...      ...
1051  1008          6    72.73
1052  1009          6    61.36
1053  1011          6    79.55
1054     7          7    72.59
1055     8          8     1.49

[1056 rows x 3 columns]